---
name: Main
'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

env:
  IMAGE_NAME: ${{ github.repository }}
  PROVENANCE_FILE: "attestation.json"

jobs:
  secret-detection:
    runs-on: docker
    container:
      # yamllint disable rule:line-length
      image: ghcr.io/yelinaung/homelab/ci:2026-02-23@sha256:2e9089a3b3d162df4129b4caae2b73a760230262d9bd9812572e172059933e04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - name: Run gitleaks
        run: gitleaks detect --source . --verbose

  fmt_and_validate:
    runs-on: docker
    container:
      # yamllint disable rule:line-length
      image: ghcr.io/yelinaung/homelab/ci:2026-02-23@sha256:2e9089a3b3d162df4129b4caae2b73a760230262d9bd9812572e172059933e04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        run: terraform init -backend=false
      - name: Terraform Validate
        run: terraform validate -no-color

  tflint:
    runs-on: docker
    container:
      # yamllint disable rule:line-length
      image: ghcr.io/yelinaung/homelab/ci:2026-02-23@sha256:2e9089a3b3d162df4129b4caae2b73a760230262d9bd9812572e172059933e04
    needs: [fmt_and_validate]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Show TFLint version
        run: tflint --version
      - name: Run TFLint
        run: tflint -f compact --recursive

  cloudflare_validate:
    runs-on: docker
    container:
      # yamllint disable rule:line-length
      image: ghcr.io/yelinaung/homelab/ci:2026-02-23@sha256:2e9089a3b3d162df4129b4caae2b73a760230262d9bd9812572e172059933e04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Terraform fmt
        run: terraform -chdir=cloudflare fmt -check
      - name: Terraform Init
        run: terraform -chdir=cloudflare init
      - name: Terraform Validate
        run: terraform -chdir=cloudflare validate -no-color
