---
name: Main
'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

env:
  IMAGE_NAME: ${{ github.repository }}
  PROVENANCE_FILE: "attestation.json"

jobs:
  secret-detection:
    runs-on: docker
    container:
      image: ghcr.io/yelinaung/homelab/ci:2026-02-23
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run gitleaks
        run: gitleaks detect --source . --verbose

  fmt_and_validate:
    runs-on: docker
    container:
      image: ghcr.io/yelinaung/homelab/ci:2026-02-23
    steps:
      - uses: actions/checkout@v6
      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate -no-color

  tflint:
    runs-on: docker
    container:
      image: ghcr.io/yelinaung/homelab/ci:2026-02-23
    needs: [fmt_and_validate]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Show TFLint version
        run: tflint --version
      - name: Run TFLint
        run: tflint -f compact --recursive

  cloudflare_validate:
    runs-on: docker
    container:
      image: ghcr.io/yelinaung/homelab/ci:2026-02-23
    steps:
      - uses: actions/checkout@v6
      - name: Terraform fmt
        run: terraform -chdir=cloudflare fmt -check
      - name: Terraform Init
        run: terraform -chdir=cloudflare init
      - name: Terraform Validate
        run: terraform -chdir=cloudflare validate -no-color
