---
# Install and configure Caddy web server
#
# Usage: make run playbook=install_caddy inventory=linux_hosts become=true
#
# Custom config: add -e 'caddy_caddyfile="your_config_here"'
#
# Example configurations:
#
# File server:
#   caddy_caddyfile: |
#     :80 {
#       root * /var/www/html
#       file_server
#     }
#
# Reverse proxy:
#   caddy_caddyfile: |
#     your-domain.com {
#       reverse_proxy localhost:3000
#     }
#
# Multiple sites:
#   caddy_caddyfile: |
#     site1.example.com {
#       root * /var/www/site1
#       file_server
#     }
#     site2.example.com {
#       reverse_proxy localhost:8080
#     }
- name: Install and configure Caddy
  hosts: '{{ vm_hosts | default("all")}}'
  become: true
  gather_facts: true
  vars:
    # Default Caddyfile - can be overridden per host/group
    caddy_caddyfile: |
      # Basic file server example
      :80 {
        respond "Hello from Caddy on {{ ansible_hostname }}!"
      }
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
          - curl
        state: present
        update_cache: true

    - name: Download Caddy GPG key
      ansible.builtin.get_url:
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        dest: /tmp/caddy.key
        mode: "0644"

    - name: Add Caddy GPG key to keyring
      ansible.builtin.shell: |
        set -o pipefail
        gpg --dearmor < /tmp/caddy.key > /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        chmod 644 /usr/share/keyrings/caddy-stable-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        executable: /bin/bash

    - name: Download Caddy repository configuration
      ansible.builtin.get_url:
        url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
        dest: /etc/apt/sources.list.d/caddy-stable.list
        mode: "0644"

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Caddy
      ansible.builtin.apt:
        name: caddy
        state: present

    - name: Create Caddyfile
      ansible.builtin.copy:
        content: "{{ caddy_caddyfile }}"
        dest: /etc/caddy/Caddyfile
        owner: root
        group: root
        mode: "0644"
      notify: Restart caddy

    - name: Start and enable Caddy service
      ansible.builtin.systemd:
        name: caddy
        state: started
        enabled: true

  handlers:
    - name: Restart caddy
      ansible.builtin.systemd:
        name: caddy
        state: restarted
