---
- name: Install qemu-guest-agent package
  hosts: '{{ vm_hosts | default("all")}}'
  become: true
  gather_facts: true
  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
