---
- name: Upgrade ClickStack
  hosts: '{{ vm_hosts | default("all")}}'
  become: true
  gather_facts: true
  roles:
    - role: clickstack
      vars:
        clickstack_pull: always
        clickstack_remove_orphans: true
