---
roles:
  - name: geerlingguy.node_exporter
    version: 2.2.0
  - name: geerlingguy.docker
    version: 8.0.0
  - name: robertdebock.collectd
    version: 3.1.8
collections:
  - name: community.general
    version: 13.0.0
  - name: ansible.posix
    version: 2.2.0
  - name: community.docker
    version: 5.2.0
  - name: artis3n.tailscale
    version: 1.2.1
  - name: victoriametrics.cluster
    version: 2.50.3
