---
- name: Upgrade OS (Mainly for Proxmox)
  hosts: '{{ vm_hosts | default("all")}}'
  become: true
  tasks:
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: full
