---
- name: Install Essential packages on the given servers
  hosts: '{{ vm_hosts | default("all")}}'
  become: true
  gather_facts: true
  tasks:
    - name: Install essential packages
      become: true
      ansible.builtin.apt:
        name:
          - htop
          - build-essential
          - net-tools
          - git
          - vim
          - curl
        state: present
        update_cache: true
    - name: Download starship installer
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship-install.sh
        mode: '0755'
    - name: Run starship installer
      become: false
      ansible.builtin.command:
        cmd: /tmp/starship-install.sh -y
      args:
        creates: /usr/local/bin/starship
    - name: Clone fzf repository
      become: false
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: "{{ ansible_user_dir }}/.fzf"
        version: 0.61.2
    - name: Install fzf for the user
      become: false
      ansible.builtin.command:
        cmd: "{{ ansible_user_dir }}/.fzf/install --all"
      args:
        creates: "{{ ansible_user_dir }}/.fzf/bin/fzf"
    - name: Add starship init to .bashrc
      become: false
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: 'eval "$(starship init bash)"'
        create: true
        mode: '0644'
      when:
        - ansible_user_shell is defined
        - ansible_user_shell.endswith('bash')
