---
name: lint
"on":
  push:
    paths:
      - "ansible/**"
      - ".github/workflows/lint.yaml"
      - "mise.toml"
permissions:
  contents: read
jobs:
  secret-detection:
    runs-on: [self-hosted, Linux, X64, playground-ubuntu]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run gitleaks
        run: gitleaks detect --source . --verbose

  lint:
    name: Linting
    runs-on: [self-hosted, Linux, X64, playground-ubuntu]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          persist-credentials: false
      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Install Ansible Deps
        run: mise run install-ansible-deps
      - name: Lint code with yamllint
        run: mise run lint-ansible
